version: "3.4"

services:

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    networks:
      - integration-test
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: broker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  integration-test:
    driver: bridge